//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KampanyaliUrunler
    {
        public int KampanyaID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> IndirimOrani { get; set; }
        public Nullable<decimal> EskiFiyat { get; set; }
        public Nullable<decimal> GuncelFiyat { get; set; }
        public Nullable<System.DateTime> KampanyaBaslangic { get; set; }
        public Nullable<System.DateTime> KampanyaBitis { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
