//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AktasMobilyaEntities : DbContext
    {
        public AktasMobilyaEntities()
            : base("name=AktasMobilyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminler> Adminlers { get; set; }
        public virtual DbSet<KampanyaliUrunler> KampanyaliUrunlers { get; set; }
        public virtual DbSet<Kataloglar> Kataloglars { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    }
}
